[node]
override-max-sessions = true
max-sessions = 4
detect-drivers = false
session-timeout = 1800

[[node.driver-configuration]]
max-sessions = 4
display-name = "Chrome"
stereotype = '{"browserName": "chrome", "platformName": "WIN11"}'

[[node.driver-configuration]]
max-sessions = 4
display-name = "Firefox"
stereotype = '{"browserName": "firefox", "platformName": "WIN11"}'

[[node.driver-configuration]]
max-sessions = 4
display-name = "IE"
stereotype = '{"browserName": "internet explorer", "platformName": "WIN11"}'

[[node.driver-configuration]]
max-sessions = 4
display-name = "Edge"
stereotype = '{"browserName": "MicrosoftEdge", "platformName": "WIN11"}'
